apiVersion: v1
kind: Service
metadata:
  name: hello-8010
  labels:
    app: hello-8010
spec:
  selector:
    app: hello-8010
  type: NodePort
  ports:
    - name: http
      port: 8010
      targetPort: 8010
      nodePort: 30010
